### ISSUE TITLE
Startup Error on the last update (Docker & Cloudbox)

### ISSUE THREAD

**Issue by NBSDEVApp** [ajslater/docker-mylar3#20]
Hi, since the last update my mylar3 don't work, I have the same error on launch who block the app.
I have try clean install, and savage chmod 777 for fix, but nothing have worked.
I use mylar3 on Docker with my Cloudbox server (ubuntu). Thanks

https://media.discordapp.net/attachments/486759605024587776/746281123742744587/Capture_decran_2020-08-21_a_10.14.41.png

**Comment by ajslater** [comment]
This image is now unmaintained. I recommend the linuxservio.io image: https://hub.docker.com/r/linuxserver/mylar3
